Controllers/DashboardController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SignPC.Models;
using SignPC.Services;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;


namespace SignPC.Controllers;

[Authorize]
public class DashboardController : Controller
{
    private readonly AppDbContext _context;

    public DashboardController(AppDbContext context)
    {
        _context = context;
    }


    public IActionResult Index()
    {
        var contEquipamento = _context.Equipamento.Count();
        ViewBag.ContEquipamento = contEquipamento;

        var contEquipa = _context.Equipa.Count();
        ViewBag.ContEquipa = contEquipa;

        var contMembro = _context.Membro.Count();
        ViewBag.ContMembro = contMembro;

        return View();
    }

}

Controllers/EquipaController.cs
using Microsoft.AspNetCore.Mvc;
using SignPC.Services;
using SignPC.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Filters;

namespace SignPC.Controllers
{
    
    [Authorize]
    public class EquipaController : Controller
    {
        private AppDbContext _context;

        public EquipaController (AppDbContext context){
            _context = context;
        }

        //Metodo Listar Membros
        public IActionResult Index(string  pesquisaString)
        {
          var equipa =  _context.Equipa.ToList();

          if (!String.IsNullOrEmpty(pesquisaString)) 
          {
            equipa = equipa.Where(n =>n.Id.ToString().Contains(pesquisaString.ToString()) || n.NomeEquipa.Contains(pesquisaString, StringComparison.OrdinalIgnoreCase)).ToList();

          }
          return View(equipa);
        }

        //Metodo Pegar
        [HttpGet]
        public IActionResult Adicionar()
        {
           return View();
        }

        //Metodo Adicionar Equipas
        [HttpPost]
        public async Task<IActionResult> Adicionar(Equipa equipa)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    _context.Add(equipa);
                    await _context.SaveChangesAsync();
                    TempData["Adicionar"] = "Equipa adicionada com sucesso!";
                    return RedirectToAction("Index");
                }
                catch (Exception ex) 
                {
                    ModelState.AddModelError(string.Empty,$"Erro  ao adicionar{ex.Message}");
                }
            }
            ModelState.AddModelError(string.Empty,$"Os campos são obrigatórios, preencha todos!");
            return View(equipa);
        }

        //Metodo Pegar
        [HttpGet]
        public IActionResult Alterar(int id)
        {
            var equipa = _context.Equipa.Where(x => x.Id==id).FirstOrDefault();
            return View (equipa);
        }

        //Metodo Editar
        [HttpPost]
        public async Task<IActionResult> Alterar(Equipa equipa)
        {
            if(ModelState.IsValid)
            {
                try
                {
                   var dado = _context.Equipa.Where(x => x.Id==equipa.Id).FirstOrDefault();
                   if(dado != null)
                   {
                        dado.NomeEquipa=equipa.NomeEquipa;
                   }

                   await _context.SaveChangesAsync();
                    TempData["Alterar"] = "Equipa alterada com sucesso!";
                   return RedirectToAction("Index");
                }

                catch (Exception ex) 
                {
                    ModelState.AddModelError(string.Empty,$"Erro  ao alterar{ex.Message}");
                }
            }
            ModelState.AddModelError(string.Empty,$"Os campos são obrigatórios, preencha todos!");
            return View(equipa);
        }

        //Metodo Pegar
        [HttpGet]
        public IActionResult Deletar(int id){
            var dado = _context.Equipa.Where(x => x.Id==id).FirstOrDefault();
            return View(dado);
        }

        [HttpPost]
        public async Task<IActionResult> Deletar(Equipa equipa)
        {
                try
                {
                   var dado = _context.Equipa.Where(x => x.Id==equipa.Id).FirstOrDefault();
                   if(dado != null)
                   {
                        _context.Remove(dado);
                        await _context.SaveChangesAsync();
                        TempData["Deletar"] = "Equipa deletada com sucesso!";
                        return RedirectToAction("Index");
                   }
                }

                catch (Exception ex) 
                {
                    ModelState.AddModelError(string.Empty,$"Está vazia!{ex.Message}");
                }
            ModelState.AddModelError(string.Empty,$"Erro ao deletar.");
            return View(equipa);
        }
    }       
}

Controllers/EquipamentoController.cs
using Microsoft.AspNetCore.Mvc;
using SignPC.Services;
using SignPC.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Filters;



namespace SignPC.Controllers
{
    [Authorize]
    public class EquipamentoController : Controller
    {
        private AppDbContext _context;

        public EquipamentoController (AppDbContext context){
            _context = context;
        }

        //Metodo Listar Equipas
        public IActionResult Index(string  pesquisaString)
        {
          var equipamento =  _context.Equipamento.ToList();
            if (!String.IsNullOrEmpty(pesquisaString)) 
            {
            equipamento = equipamento.Where(n => n.Id.ToString().Contains(pesquisaString.ToString()) || n.NomeEquipamento.Contains(pesquisaString, StringComparison.OrdinalIgnoreCase) 
            ||n.Estado.ToString().Contains(pesquisaString, StringComparison.OrdinalIgnoreCase)).ToList();
            }
          return View(equipamento);
        }

        //Metodo Pegar
        [HttpGet]
        public IActionResult Adicionar()
        {
           return View();
        }

        //Metodo Adicionar Equipas
        [HttpPost]
        public async Task<IActionResult> Adicionar(Equipamento equipamento)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    _context.Add(equipamento);
                    await _context.SaveChangesAsync();
                    TempData["Adicionar"] = "Equipamento adicionado com sucesso!";
                    return RedirectToAction("Index");
                }
                catch (Exception ex) 
                {
                    ModelState.AddModelError(string.Empty,$"Erro  ao adicionar{ex.Message}");
                }
            }
            ModelState.AddModelError(string.Empty,$"Preencha os campos!");
            return View(equipamento);
        }

        //Metodo Pegar
        [HttpGet]
        public IActionResult Alterar(int id)
        {
            var equipamento = _context.Equipamento.Where(x => x.Id==id).FirstOrDefault();
            return View (equipamento);
        }

        //Metodo Editar
        [HttpPost]
        public async Task<IActionResult> Alterar(Equipamento equipamento)
        {
            if(ModelState.IsValid)
            {
                try
                {
                   var dado = _context.Equipamento.Where(x => x.Id==equipamento.Id).FirstOrDefault();
                   if(dado != null)
                   {
                        dado.NomeEquipamento=equipamento.NomeEquipamento;
                        dado.Tipo=equipamento.Tipo;
                        dado.Descricao=equipamento.Descricao;
                        dado.Estado=equipamento.Estado;
                   }

                   await _context.SaveChangesAsync();
                    TempData["Alterar"] = "Equipamento alterado com sucesso!";
                   return RedirectToAction("Index");
                }

                catch (Exception ex) 
                {
                    ModelState.AddModelError(string.Empty,$"Erro  ao alterar{ex.Message}");
                }
            }
            ModelState.AddModelError(string.Empty,$"Preencha os campos!");
            return View(equipamento);
        }

        //Metodo Pegar
        [HttpGet]
        public IActionResult Deletar(int id){
            var dado = _context.Equipamento.Where(x => x.Id==id).FirstOrDefault();
            return View(dado);
        }

        //Metodo Deletar
        [HttpPost]
        public async Task<IActionResult> Deletar(Equipamento equipamento)
        {
                try
                {
                   var dado = _context.Equipamento.Where(x => x.Id==equipamento.Id).FirstOrDefault();
                   if(dado != null)
                   {
                        _context.Remove(dado);
                        await _context.SaveChangesAsync();
                        TempData["Deletar"] = "Equipamento deletado com sucesso!";
                        return RedirectToAction("Index");
                   }
                }

                catch (Exception ex) 
                {
                    ModelState.AddModelError(string.Empty,$"Erro  ao alterar{ex.Message}");
                }
            ModelState.AddModelError(string.Empty,$"Erro ao deletar.");
            return View(equipamento);
        }
    }
}

Controllers/MembroController.cs
using Microsoft.AspNetCore.Mvc;
using SignPC.Services;
using SignPC.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Filters;

namespace SignPC.Controllers
{
    [Authorize]
    public class MembroController : Controller
    {
        private AppDbContext _context;

        public MembroController(AppDbContext context){
            _context = context;
        }

        //Metodo Listar Membros
        public IActionResult Index(string  pesquisaString)
        {
          var membros =  _context.Membro.ToList();
            if (!String.IsNullOrEmpty(pesquisaString)) 
            {
                membros = membros.Where(n => n.Id.ToString().Contains(pesquisaString.ToString()) || n.NumProcesso.Contains(pesquisaString)
                || n.NomeMembro.Contains(pesquisaString, StringComparison.OrdinalIgnoreCase) || n.Ano.ToString().Contains(pesquisaString, StringComparison.OrdinalIgnoreCase) || n.Genero.ToString().Contains(pesquisaString, StringComparison.OrdinalIgnoreCase) || n.Curso.ToString().Contains(pesquisaString, StringComparison.OrdinalIgnoreCase) ||
                n.EmailMembro.Contains(pesquisaString, StringComparison.OrdinalIgnoreCase) || n.RefEquipa.Contains(pesquisaString, StringComparison.OrdinalIgnoreCase)).ToList();

            }
          return View(membros);
        }

        //Metodo Pegar
        [HttpGet]
        public IActionResult Adicionar()
        {
           return View();
        }

        //Metodo Adicionar Membros
        [HttpPost]
        public async Task<IActionResult> Adicionar(Membro membro)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    _context.Add(membro);
                    await _context.SaveChangesAsync();
                    TempData["Adicionar"] = "Membro adicionado com sucesso!";
                    return RedirectToAction("Index");
                }
                catch (Exception ex) 
                {
                    ModelState.AddModelError(string.Empty,$"Erro  ao adicionar{ex.Message}");
                }
            }
            ModelState.AddModelError(string.Empty,$"Preencha os campos!");
            return View(membro);
        }

        //Metodo Pegar
        [HttpGet]
        public IActionResult Alterar(int id)
        {
            var membrodado = _context.Membro.Where(x => x.Id==id).FirstOrDefault();
            return View (membrodado);
        }

        //Metodo Editar
        [HttpPost]
        public async Task<IActionResult> Alterar(Membro membro)
        {
            if(ModelState.IsValid)
            {
                try
                {
                   var dado = _context.Membro.Where(x => x.Id==membro.Id).FirstOrDefault();
                   if(dado != null)
                   {
                        dado.NumProcesso=membro.NumProcesso;
                        dado.NomeMembro=membro.NomeMembro;
                        dado.Genero=membro.Genero;
                        dado.EmailMembro=membro.EmailMembro;
                        dado.Curso=membro.Curso;
                        dado.Ano=membro.Ano;
                        dado.Telefone=membro.Telefone;
                        dado.RefEquipa=membro.RefEquipa;
                   }

                   await _context.SaveChangesAsync();
                   TempData["Alterar"] = "Membro alterado com sucesso!";
                   return RedirectToAction("Index");
                }

                catch (Exception ex) 
                {
                    ModelState.AddModelError(string.Empty,$"Erro  ao alterar{ex.Message}");
                }
            }
            ModelState.AddModelError(string.Empty,$"Preencha os campos!");
            return View(membro);
        }

         //Metodo Pegar
        [HttpGet]
        public IActionResult Deletar(int id){
            var dado = _context.Membro.FirstOrDefault(x => x.Id==id);
            return View(dado);
        }

        //Metodo Deletar
        [HttpPost]
        public async Task<IActionResult> Deletar(Membro membro)
        {
                try
                {
                   var dado = _context.Membro.FirstOrDefault(x => x.Id==membro.Id);
                   if(dado != null)
                   {
                        _context.Remove(dado);
                        await _context.SaveChangesAsync();
                        TempData["Deletar"] = "Membro deletado com sucesso!";
                        return RedirectToAction("Index");
                   }
                }

                catch (Exception ex) 
                {
                    ModelState.AddModelError(string.Empty,$"Está vazia{ex.Message}");
                }
            ModelState.AddModelError(string.Empty,$"Erro ao deletar.");
            return View(membro);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-PT">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>@ViewData["Title"]</title>

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

  <link rel="stylesheet" href="~/AdminLTE/plugins/fontawesome-free/css/all.min.css">
  <link rel="icon" href="~~/uniluanda.ico"/>

  <link rel="stylesheet" href="~/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">

  <link rel="stylesheet" href="~/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css">

  <link rel="stylesheet" href="~/AdminLTE/plugins/jqvmap/jqvmap.min.css">

  <link rel="stylesheet" href="~/AdminLTE/dist/css/adminlte.min.css">

  <link rel="stylesheet" href="~/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">

  <link rel="stylesheet" href="~/AdminLTE/plugins/daterangepicker/daterangepicker.css">

  <link rel="stylesheet" href="~/AdminLTE/plugins/summernote/summernote-bs4.min.css">

</head>
<body class="layout-fixed sidebar-mini sidebar-mini-md sidebar-collapse control-sidebar-slide-open sidebar-mini-xs" style="height: auto;">

<div class="wrapper">
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="~/AdminLTE/dist/img/uniluandalogo.png" alt="uniluandalogo" height="90" width="90">
  </div>
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
    </ul>
  </nav>

  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a class="brand-link" asp-action="Index">
      <img src="~/AdminLTE/dist/img/uniluandalogo.png" alt="Logo UniLuanda" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light" style="color: #ceae55;">INSTIC SIGN-PC</span>
    </a>

    <div class="sidebar">
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
              <i class="nav-icon fas fa-chart-line"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-right right"></i>
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" asp-controller="Membro" asp-action="Index">
              <i class="nav-icon fas fa-user"></i>
              <p>
                Membros
                <i class="right fas fa-angle-right right"></i>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Equipa" asp-action="Index">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Equipas
                <i class="right fas fa-angle-right right"></i>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Equipamento" asp-action="Index">
              <i class="nav-icon fas fa-desktop"></i>
              <p>
                Equipamentos
                <i class="fas fa-angle-right right"></i>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Conta" asp-action="Index">
              <i class="nav-icon fas fa-user-tie"></i>
              <p>
                Administradores
                <i class="fas fa-angle-right right"></i>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Conta" asp-action="Logout">
              <i class="nav-icon fas fa-door-open"></i>
              <p>
                Sair
              </p>
            </a>
          </li>
      </nav>
    </div>
  </aside>

    <div class="content-wrapper">
      <section class="content">
        <div class="container-fluid">
          <main role="main" class="pb-3">
            @RenderBody()
          </main>
        </div>
      </section>
    </div>

  <div class="row pt-5">
    <footer class="main-footer">
    <p class="text-center  text-muted"><strong>Powered by ACM-INSTIC, Copyright&copy; 2024.</strong></p>
    </footer> 
  </div>
</div>

<script src="~/AdminLTE/plugins/jquery/jquery.min.js"></script>
<script src="~/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<script src="~/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/css/wwwroot/site.js"></script>
<script src="~/AdminLTE/plugins/chart.js/Chart.min.js"></script>
<script src="~/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<script src="~/AdminLTE/dist/js/adminlte.js"></script>
<script src="~/AdminLTE/dist/js/pages/dashboard.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>